version: '3.2'

services:
  ml-workspace:
    image: ${KOTHA_IMAGE:-khulnasoft/kotha:latest}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - 8080:8080

volumes:
  ml-workspace: