kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: 192.168.0.0/16
  serviceSubnet: 10.96.0.0/12
nodes:
  - role: control-plane
    image: kindest/node:v1.23.4
    extraPortMappings:
      - containerPort: 30010
      - containerPort: 30011
      - containerPort: 30012
      - containerPort: 30013
