name: Build Pipeline

on:
  workflow_dispatch:
    inputs:
      args:
        description: Build arguments passed to the build script
        required: false
        default: "--make --force"
      working_directory:
        description: Working directory from where the build command is run
        required: false
        default: "."
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get host IP
        run: echo "_HOST_IP=$(hostname -I | cut -d ' ' -f 1)" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run build scripts
        uses: ./.github/actions/build-environment
        with:
          build_args: ${{ github.event.inputs.args }}
          working_directory: ${{ github.event.inputs.working_directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
