name: Issue Manager

on:
  schedule:
    - cron: "15 8 * * *"
  issue_comment:
    types:
      - created
  issues:
    types:
      - labeled
  pull_request_target:
    types:
      - labeled
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      # - name: Install dependencies
      #   run: npm ci

      # - name: Run issue manager
      #   run: npx issue-manager --token="${{ secrets.GITHUB_TOKEN }}" --config=config.json
